version: "3"
services: 
  app:
    image: ruby:2.6.6-buster
    working_dir: /app
    env_file:
      - .docker-env
    entrypoint: ""
    command: |
      /bin/sh -c "gem install rspec-core:3.8.1 rspec:3.8.0
      bundle install
      while true; do echo hello world; sleep 10; done"
    depends_on: 
      - elasticsearch
    volumes:
      - ./:/app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    ports:
      - 9200:9200
      - 9300:9300
