version: "3"
services: 
  app:
    image: "mosac/rails-start:2.6.3-rails5.2.3"
    working_dir: /app
    env_file:
      - .docker-env
    entrypoint: ""
    command: "/bin/bash"
    ports: 
      - 3000:3000
    volumes:
      - ./:/app
