version: 2
jobs:
  do-rspec:
    working_directory: /app
    docker:
    - image: mosac/rails-start:2.6.3-rails5.2.3
    - image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
      environment:
        discovery.type: single-node
    steps:
    - checkout
    - run:
        command: while ! nc -z localhost 9200; do sleep 0.1; done
    - run:
        command: /app/spec/es_scripts/7.x.start.sh
    - run:
        command: bundle install
    - run:
        command: bundle exec rspec
workflows:
  version: 2
  rspec:
    jobs:
    - do-rspec

# Original config.yml file:
# # Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
# version: 2.1
# 
# executors:
#   base-rails:
#     working_directory: /app
#     docker:
#       - image: mosac/rails-start:2.6.3-rails5.2.3
#       - image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
#         environment:
#           \"discovery.type\": \"single-node\"
# 
# jobs:
#   do-rspec:
#     executor: base-rails
#     steps:
#       - checkout
#       - run: while ! nc -z localhost 9200; do sleep 0.1; done 
#       - run: /app/spec/es_scripts/7.x.start.sh
#       - run: bundle install
#       - run: bundle exec rspec
# 
# # Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
# workflows:
#   version: 2
#   rspec:
#     jobs:
#       - do-rspec