name: Build and Publish Ruby Gem on Tag Pushes
on:
  push:
    tags:
      - 'v*'

jobs:
  build-gem:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and Publish Ruby Gem on Tag Pushes
      uses: jstastny/publish-gem-to-github@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: Aramassa
