name: Spec
on: push

jobs:
  rspec:
    name: Rspec with ElasticSearch
    runs-on: ubuntu-latest
    # `container-job`と実行されるサービスコンテナ
    services:
      # サービスコンテナへのアクセスに使われるラベル
      elasticsearch:
        # Docker Hubのイメージ
        image: aramassa/elastic_mini_query_test:7.1.1
        ports:
          - 9200:9200
        env:
          "discovery.type": "single-node"
        options: >-
          --health-cmd "curl -O http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=300s"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 12
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Cache bundler modules
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Prepare Spec
        run: |
          bundle config path vendor/bundle
          bundle install -j4
          bundle exec rake spec:data:prepare
          bundle exec rspec
      - name: Do Spec
        run: |
          bundle exec rspec
    
    